### ISSUE TITLE
Error running python-wizard.py

### ISSUE THREAD

**Issue by DanC4** [ptwz/python_wizard#11]
When I try to run python-wizard.py, I get this rather cryptic error code:
```
Traceback (most recent call last):
  File "python_wizard.py", line 71, in <module>
    b=Buffer.fromWave(args.filename)
  File "C:\Users\laure\Documents\python_wizard-master\python_wizard-master\pywizard\Buffer.py", line 32, in fromWave
    assert(max(d2) <= 1)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I don't know anything about this error, except that I have already seen this while using the numpy module.

**Comment by ptwz** [comment]
Sorry about that rather stupid message. It seems you tried to import a stereo file. See #10 
Should be fixed now, as far as it now gives a less cryptic message.
