### ISSUE TITLE
Add Instruction that you need Old Version of python and scipy for it to work 

### ISSUE THREAD

**Issue by christurnerchris** [ptwz/python_wizard#23]
The python program wont work with new versions of SCIPY and Python.
you need the old versions - I got it to work using python 3.7.6 and SCIPY 1.2.2 (both 32 bit from 2020 ish) 
may be add that to the instructions - save alot of frustration out there. 
chris

**Comment by ptwz** [comment]
Should be fixed in 6469ae5. Hope to have found all deprecated items, quite a hunt...
