### ISSUE TITLE
audio output

### ISSUE THREAD

**Issue by deladriere** [ptwz/python_wizard#3]
Any plan to have the audio output from the command line?
It would be useful to help to tweak the parameters with some audio feedback
thanks

**Comment by ptwz** [comment]
Yes, that's my project for the holidays.

**Comment by jaybird110127** [comment]
Wow I just found this project. I've been looking for a command line en/decoder for TMS chips for years! Any chance of adding a decoder? In my opinion, bonus points if it does *not* do any sanity checking so I could throw random garbage or data that's not LPC at it and get cool weird circuit bending noises!

**Comment by ptwz** [comment]
As now a lpcplayer is provided both inside the UI (if you have pyaudio installed) and as a standalone command line tool, I'll close this issue.
